package com.keystone.enums;

public enum NotificationType {
    WORK_ORDER_ASSIGNED,
    WORK_ORDER_STATUS_CHANGED,
    WORK_ORDER_COMPLETED,
    WORK_ORDER_CLOSED,
    WORK_ORDER_CANCELLED,
    SLA_AT_RISK,
    SLA_BREACHED,
    SERVICE_REQUEST,
    SERVICE_REQUEST_SUBMITTED,
    SERVICE_REQUEST_ACKNOWLEDGED,
    SERVICE_REQUEST_CONVERTED,
    SERVICE_REQUEST_REJECTED,
    PART_LOW_STOCK,
    GENERAL
}
